### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dajare** [ncwmail/earl-derr-biggers_behind-that-curtain#1]
### Content

- [x] All chapter*.xhtml files need their chapter title wrapper tweaked: `<h3...` should be `<p...`; see the [third example in SEMos](https://standardebooks.org/manual/1.7.4/single-page#6.2.1.6.3). I'm guessing you know your regex, but just in case it helps: search on `<h3(.*?)</h3>`, and replace with `<p$1</p>`.
- [x] chapter-1.xhtml:41: `<i epub:type="se:name.publication.newspaper">Atlantic Monthly</i>.”` = should be a magazine rather than newspaper?

### colophon.xhtml

- [x] `<abbr epub:type="z3998:given-name">` wrapper needed for initials in:
    - Norman C. Walz
    - David T. Jones
- [x] IA URL `https://archive.org/details/behindthatcurtai0000earl/mode/2up`: delete `/mode/2up`
(see [SEMoS 9.1.6.](https://standardebooks.org/manual/1.7.4/single-page#9.1.6))

### content.opf

- [x] The same subject is duplicated as both `subject-1` and `subject-2` : \#2 should be deleted.
- [x] Both the previous books in this series have "Adventure" also for `<meta property="se:subject">`: worth adding this here, too, I think.
- [x] The SHORT description [shouldn't use the character's name](https://standardebooks.org/manual/1.7.4/single-page#9.6.1.2); "A Chinese detective..." was used in one of the earlier books, and would work here, too.
- [x] In LONG description:
    - `Subsequently, Sir Bruce` > `Subsequently, Sir Frederic`
    - I would recast the last clause (`; and the novel was adapted...`) as its own sentence (`. The novel was adapted...`), but it's your call. :)
- [x] `<dc:source>https://archive.org/details/behindthatcurtai0000earl/mode/2up</dc:source>` : should have the same form as the colophon (see above).

**Comment by ncwalz** [comment]
Many thanks. I addressed all of the issues and followed your excellent advice on the rest.

**Comment by dajare** [comment]
Good stuff - almost there! 

1. *Atlantic Monthly* [still needs](https://github.com/ncwmail/earl-derr-biggers_behind-that-curtain/blob/32bba7c85f7eec3b0b083cc821e3ef4d8643313c/src/epub/text/chapter-1.xhtml#L41) its semantics changed from `newspaper` to `magazine` (see [Wikipedia](https://en.wikipedia.org/wiki/The_Atlantic)). (Which also makes more sense for that dialogue, too - getting out of newspaper work to the trendy magazine!)
1. There's a bit more detritus to clean out of content.opf - need to [delete lines 34-35](https://github.com/ncwmail/earl-derr-biggers_behind-that-curtain/blob/32bba7c85f7eec3b0b083cc821e3ef4d8643313c/src/epub/content.opf#L34), left over from `subject-2`

Once those are done, it will be ready for Alex. Thanks!
